notepad/notepad/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.edit import UpdateView

urlpatterns = patterns('',
                       url(r'^$', 
                           'notepad.views.home', 
                           name='home'),
                       url(r'^notas/(?P<id_nota>\d+)/$', 
                           'notepad.views.nota', 
                           name='nota'),
                      )

notepad/notepadProject/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('notepad.urls', namespace = "notepad")),
    url(r'^admin/', admin.site.urls),
]

notepad/notepad/models.py
# -*- encoding: utf-8 -*-
from __future__ import unicode_literals


from django.db import models

# Create your models here.
from django.contrib.auth.models import User

class Note(models.Model):
    title = models.CharField('Título',max_length=32)
    content = models.TextField('Contenido')
    date = models.DateTimeField('Fecha', auto_now_add=True)
    user = models.ForeignKey(User)
    user.verbose_name = 'Usuario'
    
    def __str__(self):
        return self.title
    
    class Meta():
        verbose_name = 'Nota'
    

notepad/notepad/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import render_to_response, render, redirect
from django.template import RequestContext
# Create your views here.
from notepad.models import Note

def home(request):
    context = RequestContext(request)
    notas = Note.objects.all()
    context['usuario_actual'] = request.user
    context['notas'] = notas
    return render_to_response("index.html", context)

def nota(request, id_nota):
    context = RequestContext(request)
    nota = Note.objects.get(pk=id_nota)    
    context['nota'] = nota
    return render_to_response("nota.html", context)

notepad/notepad/templates/base.html
<style>
 body{
  background-color: red;
     
     
 }
</style>
<body>
<h1>Sistema de Gestión de Notas</h1>
<code>Welcome to mi sistema</code>
<hr>
{% block content %}

{% endblock %}
</body>

notepad/notepad/templates/index.html
{% extends 'base.html' %}

{% block content %}
<ul>
    {% for n in notas %}
        <li><a href="{% url 'notepad:nota' n.id %}">{{n.title}}</a></li>
    {% endfor %}

</ul>
{% endblock %}

notepad/notepad/templates/nota.html
{% extends 'base.html' %}

{% block content %}

<h1>{{nota.title}}</h1>
<h4 style="color: blue">{{nota.date}}  -- {{nota.user}}</h4>
<p>{{nota.content}}</p>

{% endblock %}