blogEjemplo/blog/urls.py
from django.conf.urls import patterns, include, url
from blog.models import *
from blog.views import *

urlpatterns = patterns('',
   url(r'^post/(?P<id_post>\d+)/$', 
       'blog.views.post', 
       name='post'),
   url(r"", "blog.views.main"),
)

blogEjemplo/blogEjemplo/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from blog.views import *
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^', include('blog.urls', namespace='home')), 
    url(r'^admin/', include(admin.site.urls)), 
)

blogEjemplo/blog/models.py
# -*- encoding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django.contrib import admin
from django.core.mail import send_mail

#notify = False

class Post(models.Model):
    title = models.CharField(max_length=60)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    
    CATEGORIAS = (
        ("0", 'Linux'),
        ("1", 'dJango'),        
        ("2", 'Tutos'),
    )
    categorias = models.CharField(max_length=6,
                                      choices=CATEGORIAS,
                                      default="0")
    
    def __unicode__(self):
        return self.title





### Admin

class PostAdmin(admin.ModelAdmin):
    search_fields = ["title"]
    display_fields = ["title", "created","categorias"]
    
#NO IMPLEMENTADO    
class Comment(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=60)
    body = models.TextField()
    post = models.ForeignKey(Post)

    def __unicode__(self):
        return unicode("%s: %s" % (self.post, self.body[:60]))

    
    
    '''
    #ESTO ES PARA ENVIAR UN MAIL CADA VEZ QUE ALQUIEN COMENTA
    #TODO: NO ESTÁ IMPLEMENTADO
    def save(self, *args, **kwargs):
        """Email when a comment is added."""
        if "notify" in kwargs and kwargs["notify"] == True:
            message = "Se realizo un comentario en el post '%s', por el usuario '%s': \n\n%s" % (self.post, self.author,
                                                                         self.body)
            from_addr = "no-reply@mydomain.com"
            recipient_list = ["myemail@mydomain.com"]
            send_mail("New comment added", message, from_addr, recipient_list)

        if "notify" in kwargs: del kwargs["notify"]
        super(Comment, self).save(*args, **kwargs)

class CommentAdmin(admin.ModelAdmin):
    display_fields = ["post", "author", "created"]
    '''

blogEjemplo/blog/views.py
import time
from calendar import month_name

from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render_to_response
from django.contrib.auth.decorators import login_required
from django.core.context_processors import csrf
from django.core.paginator import Paginator, InvalidPage, EmptyPage
from django.core.urlresolvers import reverse
from django.template import RequestContext

from blog.models import *
from django.forms import ModelForm

def main(request):
    """Main listing."""
    context = RequestContext(request)
    posts = Post.objects.all().order_by("-created")
    paginator = Paginator(posts, 3)
    try: page = int(request.GET.get("page", '1'))
    except ValueError: page = 1

    try:
        posts = paginator.page(page)
    except (InvalidPage, EmptyPage):
        posts = paginator.page(paginator.num_pages)

    context.update(dict(posts=posts, user=request.user,
                        post_list=posts.object_list, months=mkmonth_lst()))
    return render_to_response("list.html", context)

def post(request, id_post):
    """Single post with comments and a comment form."""
    context = RequestContext(request)
    post = Post.objects.get(pk=id_post)
    print request.method
    if 'POST' in request.method:
        author = request.POST['author']
        content = request.POST['content']
        comentario = Comment(author=author, 
                             body=content,
                             post=post)
        comentario.save()
    comments = Comment.objects.filter(post=post)
    #form=CommentForm()
    context.update(dict(post=post, user=request.user, comments=comments))#, comments=comments)
    context.update(csrf(request))
    return render_to_response("post.html", context)



'''
class CommentForm(ModelForm):
    class Meta:
        model = Comment
        exclude = ["post"]

def delete_comment(request, post_pk, pk=None):
    """Delete comment(s) with primary key `pk` or with pks in POST."""
    if request.user.is_staff:
        if not pk: pklst = request.POST.getlist("delete")
        else: pklst = [pk]

        for pk in pklst:
            Comment.objects.get(pk=pk).delete()
        return HttpResponseRedirect(reverse("dbe.blog.views.post", args=[post_pk]))

def add_comment(request, pk):
    """Add a new comment."""
    p = request.POST

    if p.has_key("body") and p["body"]:
        author = "Anonymous"
        if p["author"]: author = p["author"]
        comment = Comment(post=Post.objects.get(pk=pk))

        # save comment form
        cf = CommentForm(p, instance=comment)
        cf.fields["author"].required = False
        comment = cf.save(commit=False)

        # save comment instance
        comment.author = author
        notify = True
        if request.user.username == "ak": notify = False
        comment.save(notify=notify)
    return HttpResponseRedirect(reverse("dbe.blog.views.post", args=[pk]))
'''
def mkmonth_lst():
    """Make a list of months to show archive links."""
    if not Post.objects.count(): return []

    # set up vars
    year, month = time.localtime()[:2]
    first = Post.objects.order_by("created")[0]
    fyear = first.created.year
    fmonth = first.created.month
    months = []

    # loop over years and months
    for y in range(year, fyear-1, -1):
        start, end = 12, 0
        if y == year: start = month
        if y == fyear: end = fmonth-1

        for m in range(start, end, -1):
            months.append((y, m, month_name[m]))
    return months

def month(request, year, month):
    """Monthly archive."""
    posts = Post.objects.filter(created__year=year, created__month=month)
    return render_to_response("list.html", dict(post_list=posts, user=request.user,
                                                months=mkmonth_lst(), archive=True))

blogEjemplo/blog/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load static %}

<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Clean Blog</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"/>

    <!-- Custom CSS -->
    <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">Start Bootstrap</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="index.html">Home</a>
                    </li>
                    <li>
                        <a href="about.html">About</a>
                    </li>
                    <li>
                        <a href="post.html">Sample Post</a>
                    </li>
                    <li>
                        <a href="contact.html">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url('{% static 'img/home-bg.jpg' %}')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>Clean Blog</h1>
                        <hr class="small">
                        <span class="subheading">A Clean Blog Theme by Start Bootstrap</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <div id="container">
            {% block content %}{% endblock %}
        </div>

    <hr>

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; Your Website 2014</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="{% static 'js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{% static 'js/clean-blog.min.js' %}"></script>

</body>

</html>

blogEjemplo/blog/templates/bbase.html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title>{% block title %}Blog{% endblock %}</title>
    <!-- <meta http-equiv="refresh" content="2">  -->
    <link rel="stylesheet" href="/media/style.css" type="text/css" media="screen"
      charset="utf-8" />

    <style type="text/css">
        * {
            color: #555;
            font-size: 0.95em;
        }

        #menu a {
            text-decoration: none;
            background: #eee;
            border-top: 1px solid #ccc;
            border-bottom: 1px solid #ccc;
            border-right: 2px solid #fff;
            padding-right: 3px;
            padding-left: 3px;
            color: #777;
            font-size: 0.9em;
        }

        a:hover {
            background: #eeebeb;
            border-top: 1px solid #aaa;
            border-bottom: 1px solid #aaa;
            color: #555;
        }

        #container { margin: auto; width: 800px; border: 0px solid; }
        p { font-size: 1.1em; }
        h3 { margin-right: 30px; display: inline; }
        h1 { font-size: 22px; margin-right: 30px; color: red; text-transform: uppercase; text-align: center;}
    </style>

</head>

<body>
    <div id="sidebar"> {% block sidebar %} {% endblock %} </div>
    <div id="container">
        <h1>Este es el blog de sexto</h1>
        <div id="menu">
            {% block nav-global %}

                <!-- MENU -->

                <h2>Si no te gusta el estilo, cambialo...</h2>
                {% if user.is_staff %}

                {% endif %}

            {% endblock %}
        </div>

        <div id="content">
            {% block content %}{% endblock %}
        </div>
    </div>

</body>
</html>

blogEjemplo/blog/templates/blog/bbase.html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title>{% block title %}Blog{% endblock %}</title>
    <!-- <meta http-equiv="refresh" content="2">  -->
    <link rel="stylesheet" href="/media/style.css" type="text/css" media="screen"
      charset="utf-8" />

    <style type="text/css">
        * {
            color: #555;
            font-size: 0.95em;
        }

        #menu a {
            text-decoration: none;
            background: #eee;
            border-top: 1px solid #ccc;
            border-bottom: 1px solid #ccc;
            border-right: 2px solid #fff;
            padding-right: 3px;
            padding-left: 3px;
            color: #777;
            font-size: 0.9em;
        }

        a:hover {
            background: #eeebeb;
            border-top: 1px solid #aaa;
            border-bottom: 1px solid #aaa;
            color: #555;
        }

        #container { margin: auto; width: 800px; border: 0px solid; }
        p { font-size: 1.1em; }
        h3 { margin-right: 30px; display: inline; }
    </style>

</head>

<body>
    <div id="sidebar"> {% block sidebar %} {% endblock %} </div>
    <div id="container">
        <div id="menu">
            {% block nav-global %}

                <!-- MENU -->
                <h3>MyBlog</h3>
                {% if user.is_staff %}
                <a href="{% url admin:index %}">Admin</a>
                     <a href="{% url admin:blog_post_add %}">Add post</a>
                {% endif %}

            {% endblock %}
        </div>

        <div id="content">
            {% block content %}{% endblock %}
        </div>
    </div>

</body>
</html>

blogEjemplo/blog/templates/blog/list.html
{% extends "bbase.html" %}

{% block sidebar %}
    <style type="text/css">
        #sidebar { float: right; border: 1px dotted #ccc; padding: 4px; }
        a { margin-left: 15px; }
    </style>
    <div id="sidebar">
        Monthly Archive
        <p>
        {% for month in months %}
            {% ifchanged month.0 %} {{ month.0 }} <br /> {% endifchanged %}
            <a href="{% url blog.views.month month.0 month.1 %}">{{ month.2 }}</a> <br />
        {% endfor %}
        </p>
    </div>
{% endblock %}

{% block content %}
    <style type="text/css">
        .main { margin-left: 25px; margin-top: 30px; }
        .time { font-size: 0.8em; margin-top: 2px; }
        .body { font-size: 1.1em; margin-top: 2px; }
        .commentlink { text-align: right; }
        .step-links a { font-size: 0.89em; }
        .title {
            font-size: 1.4em; margin-top: 20px; border-bottom: 1px solid #ccc;
            padding-left: 4px; margin-left: 5px;
        }
        .messages { margin-left: 20px; }
        .pagination { margin-top: 20px; margin-left: -20px; }
    </style>
    <div class="main">

        <!-- Posts  -->
            {% for post in post_list %}
                <div class="title">{{ post.title }}</div>
                <ul>
                    <div class="time">{{ post.created }}</div>
                    <div class="body">{{ post.body|linebreaks }}</div>
                    <div class="commentlink">
                    <a href="{% url blog.views.post post.pk %}">Comments ({{ post.comment_set.count }})</a>
                    </div>
                </ul>
            {% endfor %}

        <!-- Next/Prev page links  -->
        {% if not archive and posts.object_list and posts.paginator.num_pages > 1 %}
        <div class="pagination">
            <span class="step-links">
                {% if posts.has_previous %}
                    <a href= "?page={{ posts.previous_page_number }}">newer entries &lt;&lt; </a>
                {% endif %}

                <span class="current">
                    &nbsp;Page {{ posts.number }} of {{ posts.paginator.num_pages }}
                </span>

                {% if posts.has_next %}
                    <a href="?page={{ posts.next_page_number }}"> &gt;&gt; older entries</a>
                {% endif %}
            </span>
        </div>
        {% endif %}

    </div>

{% endblock %}

blogEjemplo/blog/templates/blog/post.html
{% extends "bbase.html" %}

{% block content %}
    <style type="text/css">
        .main { margin-left: 25px; margin-top: 30px; }
        .time { font-size: 0.8em; margin-top: 2px; }
        .comment { border: 1px solid #eee; padding: 4px; margin-bottom: 12px; }
        .body { font-size: 1.1em; margin-top: 2px; }
        .messages { margin-left: 20px; }
        .title { font-size: 14px; margin-top: 20px; border-bottom: 1px solid #ccc;color: #abc; padding-left: 4px; }

        #addc { width: 508px; background: #f5f5f5; padding: 3px; padding-bottom: 8px;
            border-bottom: 1px dotted #aaa;
            }
        #cform { background: #f5f5f5; width: 506px; padding: 4px; padding-bottom: 0px; }
        #submit { text-align: right; margin-right: 50px; width: 500px; margin-top: -5px; }

        ul { margin-bottom: 30px; }
    </style>
    <div class="main">

        <!-- Messages  -->
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}

        <!-- Post  -->
        <ul>
            <div class="title">{{ post.title }}</div>
            <ul>
                <div class="time">{{ post.created }}</div>
                <div class="body">{{ post.body }}</div>
            </ul>

            <!-- Comments  -->
            {% if comments %}
                <p>Comments:</p>
            {% endif %}

            <form action="{% url blog.views.delete_comment post.pk %}" method="POST">{% csrf_token %}
            {% for comment in comments %}
                <div class="comment">
                    <div class="time">{{ comment.created }} | {{ comment.author }}</div>
                    <div class="body">{{ comment.body|linebreaks }}</div>
                    {% if user.is_staff %}
                        <input type="checkbox" name="delete" value="{{ comment.pk }}">
                        <a href="{% url blog.views.delete_comment post.pk comment.id %}">delete</a>
                    {% endif %}
                </div>
            {% endfor %}

            {% if user.is_staff and comments %}
                <p><input type="submit" value="Delete all selected"></p>
                <br />
            {% endif %}
            </form>

            <div id="addc">Add a comment</div>
            <!-- Comment form  -->
            <form action="{% url blog.views.add_comment post.id %}" method="POST">{% csrf_token %}
                <div id="cform">
                    Name: {{ form.author }}
                    <p>{{ form.body|linebreaks }}</p>
                </div>
                <div id="submit"><input type="submit" value="Submit"></div>
            </form>
        </ul>

    </div>

{% endblock %}

blogEjemplo/blog/templates/list.html
{% extends "base.html" %}

{% block sidebar %}
    <style type="text/css">
        #sidebar { float: right; border: 1px dotted #ccc; padding: 4px; }
        a { margin-left: 15px; }
    </style>
    <div id="sidebar">
        Monthly Archive
        <p>
        {% for month in months %}
            {% ifchanged month.0 %} {{ month.0 }} <br /> {% endifchanged %}

        {% endfor %}
        </p>
    </div>
{% endblock %}

{% block content %}




    <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                {% for post in post_list %}
                <div class="post-preview">
                    <a href="{% url 'home:post' post.id %}">
                        <h2 class="post-title">
                            {{ post.title }}
                        </h2>
                        <h3 class="post-subtitle">
                            {{ post.body|linebreaks }}
                        </h3>
                    </a>
                    <p class="post-meta">Fecha: {{ post.created }}</p>
                </div>
                <hr>
                 {% endfor %}
        </div>
</div>






        <!-- Next/Prev page links  -->
        {% if not archive and posts.object_list and posts.paginator.num_pages > 1 %}
        <div class="pagination">
            <span class="step-links">
                {% if posts.has_previous %}
                    <a href= "?page={{ posts.previous_page_number }}">Entradas mas nuevas &lt;&lt; </a>
                {% endif %}

                <span class="current">
                    &nbsp;Pagina {{ posts.number }} de {{ posts.paginator.num_pages }}
                </span>

                {% if posts.has_next %}
                    <a href="?page={{ posts.next_page_number }}"> &gt;&gt; Post mas viejitos</a>
                {% endif %}
            </span>
        </div>
        {% endif %}



{% endblock %}

blogEjemplo/blog/templates/post.html
{% extends "base.html" %}

{% block content %}
    <style type="text/css">
        .main { margin-left: 25px; margin-top: 30px; }
        .time { font-size: 0.8em; margin-top: 2px; }
        .comment { border: 1px solid #eee; padding: 4px; margin-bottom: 12px; }
        .body { font-size: 1.1em; margin-top: 2px; }
        .messages { margin-left: 20px; }
        .title { font-size: 14px; margin-top: 20px; border-bottom: 1px solid #ccc;color: #000; padding-left: 4px; }

        #addc { width: 508px; background: #f5f5f5; padding: 3px; padding-bottom: 8px;
            border-bottom: 1px dotted #aaa;
            }
        #cform { background: #f5f5f5; width: 506px; padding: 4px; padding-bottom: 0px; }
        #submit { text-align: right; margin-right: 50px; width: 500px; margin-top: -5px; }

        ul { margin-bottom: 30px; }
    </style>
    <div class="main">

        <!-- Messages  -->
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}

        <!-- Post  -->
        <ul>
            <div class="title">{{ post.title }}</div>
            <ul>
                <div class="time">{{ post.created }}</div>
                <div class="body">{{ post.body }}</div>
            </ul>

            <!-- Comments  -->
            {% if comments %}
                <p>Comments:</p>
            {% endif %}

            <form action="" method="POST">{% csrf_token %}
            {% for comment in comments %}
                <div class="comment">
                    <div class="time">{{ comment.created }} | {{ comment.author }}</div>
                    <div class="body">{{ comment.body|linebreaks }}</div>
                    {% if user.is_staff %}
                        <input type="checkbox" name="delete" value="{{ comment.pk }}">
                        <a href="">delete</a>
                    {% endif %}
                </div>
            {% endfor %}

            {% if user.is_staff and comments %}
                <p><input type="submit" value="Delete all selected"></p>
                <br />
            {% endif %}
            </form>

            <div id="addc">Mete un comentario</div><hr>
            <!-- Comment form  -->
            <form action="" method="POST">
            
                {% csrf_token %}
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Autor" name='author' aria-describedby="basic-addon1"/>
                    <textarea class="form-control" placeholder="Contenido" name='content' aria-describedby="basic-addon1"></textarea>
</div>
                <div id="submit"><input type="submit" value="Submit"></div>
            
            </form>
        </ul>

    </div>

{% endblock %}

blogEjemplo/templates/bbase.html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title>{% block title %}Blog{% endblock %}</title>
    <!-- <meta http-equiv="refresh" content="2">  -->
    <link rel="stylesheet" href="/media/style.css" type="text/css" media="screen"
      charset="utf-8" />

    <style type="text/css">
        * {
            color: #555;
            font-size: 0.95em;
        }

        #menu a {
            text-decoration: none;
            background: #eee;
            border-top: 1px solid #ccc;
            border-bottom: 1px solid #ccc;
            border-right: 2px solid #fff;
            padding-right: 3px;
            padding-left: 3px;
            color: #777;
            font-size: 0.9em;
        }

        a:hover {
            background: #eeebeb;
            border-top: 1px solid #aaa;
            border-bottom: 1px solid #aaa;
            color: #555;
        }

        #container { margin: auto; width: 800px; border: 0px solid; }
        p { font-size: 1.1em; }
        h3 { margin-right: 30px; display: inline; }
        h1 { font-size: 22px; margin-right: 30px; color: red; text-transform: uppercase; text-align: center;}
    </style>

</head>

<body>
    <div id="sidebar"> {% block sidebar %} {% endblock %} </div>
    <div id="container">
        <h1>Este es el blog de sexto</h1>
        <div id="menu">            
            {% block nav-global %}
                
                <!-- MENU -->
                
                <h2>Si no te gusta el estilo, cambialo...</h2>
                {% if user.is_staff %}
                
                {% endif %}

            {% endblock %}
        </div>

        <div id="content">            
            {% block content %}{% endblock %}
        </div>
    </div>

</body>
</html>